version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      requests-dependencies:
        patterns:
          - "types-requests"
          - "requests"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
